services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=145
      - POSTGRES_DB=amigosfieis
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: